package main.api;

import main.common.APIINIT;
import main.common.LOGGER;
import main.common.TOOLS;
import main.common.ERRORCODE;
import main.module.Module;
import org.springframework.scheduling.annotation.Async;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import jakarta.annotation.Resource;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.web.bind.annotation.*;
import org.springframework.scheduling.annotation.Scheduled;
import tools.jackson.databind.JsonNode;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

//此文件由Christmas根据.xmas生成，手动修改会被覆盖
//This file is generated by Christmas according to .xmas, and manual modification will be overwritten.

@RestController
@RequestMapping("/test")
public class test {
    
    @RequestMapping(value="/test", method=RequestMethod.POST)
    @ResponseBody
    public JsonNode testPOST(HttpServletRequest request, HttpServletResponse response, @RequestBody(required = false) String requestParam){
        List<HashMap<String, Object>> selectorRetryData = new ArrayList<>();
        HashMap<String, Object> dataPool = new HashMap<>();
        ERRORCODE result = ERRORCODE.ERR_OK;
        JsonNode moduleParam;
    
        try {
            //STEP::Init data pool
            result = APIINIT.InitDataPool(dataPool, request, response, requestParam);
            LOGGER.INIT("API", "API start", dataPool);
            Module.Init(dataPool);
            if(ERRORCODE.IsError(result)){
                return null;
            }
    
            //STEP::Run task
            do{
    
                //STEP-IN::Call Module-_DataCheck
                moduleParam = TOOLS.JsonCache("""
                    {"_isClean": true, "_param": {"opt##test_value": "str##"}}
                """);
                result = Module.Start("_DataCheck", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_DataFilling
                moduleParam = TOOLS.JsonCache("""
                    {"_setting": {"test_id": "uuid", "opt##test_value": "time"}}
                """);
                result = Module.Start("_DataFilling", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_ServeDao
                moduleParam = TOOLS.JsonCache("""
                    {"_action": "insert", "_table": "test", "_isCheckAffect": true}
                """);
                result = Module.Start("_ServeDao", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_DataCheck
                moduleParam = TOOLS.JsonCache("""
                    {"_isClean": true, "_param": {}}
                """);
                result = Module.Start("_DataCheck", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
            }while (false);
    
        } catch(Exception e){
            result = ERRORCODE.ERR_Api_Exception;
            LOGGER.ERROR("API exception:"+ TOOLS.GetExceptionInfo(e), dataPool);
        } finally {
            Module.End(dataPool, result);
            JsonNode passParam = (JsonNode) dataPool.get("passParam");
            passParam = ERRORCODE.GetErrorCode(result, passParam);
            LOGGER.END("API end", passParam);
            return passParam;
        }
    }
    
    @RequestMapping(value="/testBatch", method=RequestMethod.POST)
    @ResponseBody
    public JsonNode testBatchPOST(HttpServletRequest request, HttpServletResponse response, @RequestBody(required = false) String requestParam){
        List<HashMap<String, Object>> selectorRetryData = new ArrayList<>();
        HashMap<String, Object> dataPool = new HashMap<>();
        ERRORCODE result = ERRORCODE.ERR_OK;
        JsonNode moduleParam;
    
        try {
            //STEP::Init data pool
            result = APIINIT.InitDataPool(dataPool, request, response, requestParam);
            LOGGER.INIT("API", "API start", dataPool);
            Module.Init(dataPool);
            if(ERRORCODE.IsError(result)){
                return null;
            }
    
            //STEP::Run task
            do{
    
                //STEP-IN::Call Module-_DataCheck
                moduleParam = TOOLS.JsonCache("""
                    {"_isClean": true, "_param": {"10##insert": [{"test_value": "str##"}]}}
                """);
                result = Module.Start("_DataCheck", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_DataFilling
                moduleParam = TOOLS.JsonCache("""
                    {"_setting": {"insert": [{"test_id": "uuid"}]}}
                """);
                result = Module.Start("_DataFilling", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_ServeDao
                moduleParam = TOOLS.JsonCache("""
                    {"_action": "insert batch", "_table": "test", "_target": "get##insert", "_resultKey": "result", "_isCheckAffect": true}
                """);
                result = Module.Start("_ServeDao", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_DataCheck
                moduleParam = TOOLS.JsonCache("""
                    {"_isClean": true, "_param": {"result": ""}}
                """);
                result = Module.Start("_DataCheck", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
            }while (false);
    
        } catch(Exception e){
            result = ERRORCODE.ERR_Api_Exception;
            LOGGER.ERROR("API exception:"+ TOOLS.GetExceptionInfo(e), dataPool);
        } finally {
            Module.End(dataPool, result);
            JsonNode passParam = (JsonNode) dataPool.get("passParam");
            passParam = ERRORCODE.GetErrorCode(result, passParam);
            LOGGER.END("API end", passParam);
            return passParam;
        }
    }
    
    @RequestMapping(value="/test", method=RequestMethod.DELETE)
    @ResponseBody
    public JsonNode testDELETE(HttpServletRequest request, HttpServletResponse response, @RequestBody(required = false) String requestParam){
        List<HashMap<String, Object>> selectorRetryData = new ArrayList<>();
        HashMap<String, Object> dataPool = new HashMap<>();
        ERRORCODE result = ERRORCODE.ERR_OK;
        JsonNode moduleParam;
    
        try {
            //STEP::Init data pool
            result = APIINIT.InitDataPool(dataPool, request, response, requestParam);
            LOGGER.INIT("API", "API start", dataPool);
            Module.Init(dataPool);
            if(ERRORCODE.IsError(result)){
                return null;
            }
    
            //STEP::Run task
            do{
    
                //STEP-IN::Call Module-_DataCheck
                moduleParam = TOOLS.JsonCache("""
                    {"_isClean": true, "_param": {"test_id": "str##"}}
                """);
                result = Module.Start("_DataCheck", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_ServeDao
                moduleParam = TOOLS.JsonCache("""
                    {"_action": "delete", "_table": "test", "_isCheckAffect": true}
                """);
                result = Module.Start("_ServeDao", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_DataCheck
                moduleParam = TOOLS.JsonCache("""
                    {"_isClean": true, "_param": {}}
                """);
                result = Module.Start("_DataCheck", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
            }while (false);
    
        } catch(Exception e){
            result = ERRORCODE.ERR_Api_Exception;
            LOGGER.ERROR("API exception:"+ TOOLS.GetExceptionInfo(e), dataPool);
        } finally {
            Module.End(dataPool, result);
            JsonNode passParam = (JsonNode) dataPool.get("passParam");
            passParam = ERRORCODE.GetErrorCode(result, passParam);
            LOGGER.END("API end", passParam);
            return passParam;
        }
    }
    
    @RequestMapping(value="/test", method=RequestMethod.PUT)
    @ResponseBody
    public JsonNode testPUT(HttpServletRequest request, HttpServletResponse response, @RequestBody(required = false) String requestParam){
        List<HashMap<String, Object>> selectorRetryData = new ArrayList<>();
        HashMap<String, Object> dataPool = new HashMap<>();
        ERRORCODE result = ERRORCODE.ERR_OK;
        JsonNode moduleParam;
    
        try {
            //STEP::Init data pool
            result = APIINIT.InitDataPool(dataPool, request, response, requestParam);
            LOGGER.INIT("API", "API start", dataPool);
            Module.Init(dataPool);
            if(ERRORCODE.IsError(result)){
                return null;
            }
    
            //STEP::Run task
            do{
    
                //STEP-IN::Call Module-_DataCheck
                moduleParam = TOOLS.JsonCache("""
                    {"_isClean": true, "_param": {"10##test_id": ["str##"]}}
                """);
                result = Module.Start("_DataCheck", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_DataFilling
                moduleParam = TOOLS.JsonCache("""
                    {"_setting": {"test_value": "time"}}
                """);
                result = Module.Start("_DataFilling", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_ServeDao
                moduleParam = TOOLS.JsonCache("""
                    {"_action": "update", "_table": "test", "_resultKey": "update", "_isCheckAffect": true}
                """);
                result = Module.Start("_ServeDao", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_ServeDao
                moduleParam = TOOLS.JsonCache("""
                    {"_action": "sql select", "_sql": "SELECT * FROM test WHERE test_id IN ('@test_id@')", "_selectType": "select list", "_resultKey": "result"}
                """);
                result = Module.Start("_ServeDao", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_DataCheck
                moduleParam = TOOLS.JsonCache("""
                    {"_isClean": true, "_param": {"update": "", "result": ""}}
                """);
                result = Module.Start("_DataCheck", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
            }while (false);
    
        } catch(Exception e){
            result = ERRORCODE.ERR_Api_Exception;
            LOGGER.ERROR("API exception:"+ TOOLS.GetExceptionInfo(e), dataPool);
        } finally {
            Module.End(dataPool, result);
            JsonNode passParam = (JsonNode) dataPool.get("passParam");
            passParam = ERRORCODE.GetErrorCode(result, passParam);
            LOGGER.END("API end", passParam);
            return passParam;
        }
    }
    
    @RequestMapping(value="/test", method=RequestMethod.GET)
    @ResponseBody
    public JsonNode testGET(HttpServletRequest request, HttpServletResponse response, @RequestBody(required = false) String requestParam){
        List<HashMap<String, Object>> selectorRetryData = new ArrayList<>();
        HashMap<String, Object> dataPool = new HashMap<>();
        ERRORCODE result = ERRORCODE.ERR_OK;
        JsonNode moduleParam;
    
        try {
            //STEP::Init data pool
            result = APIINIT.InitDataPool(dataPool, request, response, requestParam);
            LOGGER.INIT("API", "API start", dataPool);
            Module.Init(dataPool);
            if(ERRORCODE.IsError(result)){
                return null;
            }
    
            //STEP::Run task
            do{
    
                //STEP-IN::Call Module-_DataCheck
                moduleParam = TOOLS.JsonCache("""
                    {"_isClean": false, "_param": {"option": "str##object/list"}}
                """);
                result = Module.Start("_DataCheck", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::SELECTOR-SWITCH
                switch (TOOLS.ReadPassParam("option", dataPool)){
                    case "list":do{
                            //STEP-IN::Call Module-_DataCheck
                            moduleParam = TOOLS.JsonCache("""
                                {"_isClean": true, "_param": {"page": "int##", "pageSize": "int##"}}
                            """);
                            result = Module.Start("_DataCheck", moduleParam, dataPool);
                            if(ERRORCODE.IsError(result, new ERRORCODE[]{
                                })){
                                continue;
                            }
                            result = ERRORCODE.ERR_OK;
                            
                            //STEP-IN::Call Module-_ServeDao
                            moduleParam = TOOLS.JsonCache("""
                                {"_action": "select list", "_table": "test", "_page": "get##page", "_pageSize": "get##pageSize", "_countResultKey": "count", "_resultKey": "result"}
                            """);
                            result = Module.Start("_ServeDao", moduleParam, dataPool);
                            if(ERRORCODE.IsError(result, new ERRORCODE[]{
                                })){
                                continue;
                            }
                            result = ERRORCODE.ERR_OK;
                            
                            //STEP-IN::Call Module-_DataCheck
                            moduleParam = TOOLS.JsonCache("""
                                {"_isClean": true, "_param": {"result": "", "opt##count": ""}}
                            """);
                            result = Module.Start("_DataCheck", moduleParam, dataPool);
                            if(ERRORCODE.IsError(result, new ERRORCODE[]{
                                })){
                                continue;
                            }
                            result = ERRORCODE.ERR_OK;
                            
                        }while(false);
                        break;
                    default:do{
                            //STEP-IN::SELECTOR-CALL
                            result = this.testGet_objectFUNCTION(dataPool);
                            if(ERRORCODE.IsError(result)){
                                continue;
                            }
                            result = ERRORCODE.ERR_OK;
                            
                        }while (false);
                }
                
            }while (false);
    
        } catch(Exception e){
            result = ERRORCODE.ERR_Api_Exception;
            LOGGER.ERROR("API exception:"+ TOOLS.GetExceptionInfo(e), dataPool);
        } finally {
            Module.End(dataPool, result);
            JsonNode passParam = (JsonNode) dataPool.get("passParam");
            passParam = ERRORCODE.GetErrorCode(result, passParam);
            LOGGER.END("API end", passParam);
            return passParam;
        }
    }
    
    public ERRORCODE testGet_objectFUNCTION(HashMap<String, Object> dataPool) {
        LOGGER.DEBUG("FUNCTION testGet_object start", dataPool);
        List<HashMap<String, Object>> selectorRetryData = new ArrayList<>();
        ERRORCODE result = ERRORCODE.ERR_OK;
        LOGGER.ChangePosition("FUNCTION-testGet_object");
        JsonNode moduleParam;
    
        try {
            //STEP::Run task
            do{
    
                //STEP-IN::Call Module-_DataCheck
                moduleParam = TOOLS.JsonCache("""
                    {"_isClean": true, "_param": {"test_id": "str##"}}
                """);
                result = Module.Start("_DataCheck", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_ServeDao
                moduleParam = TOOLS.JsonCache("""
                    {"_action": "select object", "_table": "test", "_resultKey": "", "_isGetNullError": true}
                """);
                result = Module.Start("_ServeDao", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
                //STEP-IN::Call Module-_DataCheck
                moduleParam = TOOLS.JsonCache("""
                    {"_isClean": true, "_param": {"test_id": "", "test_value": ""}}
                """);
                result = Module.Start("_DataCheck", moduleParam, dataPool);
                if(ERRORCODE.IsError(result, new ERRORCODE[]{
                    })){
                    continue;
                }
                result = ERRORCODE.ERR_OK;
                
            }while (false);
        } catch(Exception e){
            result = ERRORCODE.ERR_Api_Exception;
            LOGGER.ERROR("FUNCTION exception:"+ TOOLS.GetExceptionInfo(e), dataPool);
        } finally{
            Module.End(dataPool, result);
        }
    
        LOGGER.DEBUG("FUNCTION testGet_object end", dataPool);
        return result;
    }

}